# Config file for automatic testing at travis-ci.org

sudo: false
language: python
matrix:
  include:
    - python: 3.5
      env:
        - TOX_ENV=py27
        - TOX_ENV=py33
        - TOX_ENV=py34
        - TOX_ENV=py35
    - python: 3.6
      env:
        - TOX_ENV=py36

script: tox -e $TOX_ENV

install:
    - pip install tox

notifications:
  email: false
