# Config file for automatic testing at travis-ci.org

sudo: false
language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      env: TOX_ENV=lint
      install: pip install flake8
      script: flake8 --ignore=E501,W503 lib/fontline/*.py
    - python: 3.6
      env: TOX_ENV=py36
      install:
        - pip install tox
        - pip install -r requirements.txt
      script: tox -e $TOX_ENV
    - python: 3.7
      env: TOX_ENV=py37
      install:
        - pip install tox
        - pip install -r requirements.txt
      dist: xenial
      script: tox -e $TOX_ENV
    - python: 3.8
      env: TOX_ENV=py38
      install:
        - pip install tox
        - pip install -r requirements.txt
      dist: xenial
      script: tox -e $TOX_ENV
    - python: 3.7
      dist: xenial
      env: TOX_ENV=coverage
      install:
        - pip install --upgrade coverage
        - pip install -r requirements.txt .
      script:
        - coverage run --source fontline -m py.test
        - coverage report -m
      after_success:
        - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
