# Config file for automatic testing at travis-ci.org

sudo: false
language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      env: TOX_ENV=lint
      install: pip install flake8
      script: flake8 --ignore=E501,W503 lib/fontline/*.py
    - python: 3.5
      env: TOX_ENV=py35
      install: pip install tox
      script: tox -e $TOX_ENV
    - python: 3.6
      env: TOX_ENV=py36
      install: pip install tox
      script: tox -e $TOX_ENV
    - python: 3.7
      env: TOX_ENV=py37
      install: pip install tox
      dist: xenial
      script: tox -e $TOX_ENV

notifications:
  email: false